server {

        server_name thames.chronosynclabs.com.np;

        access_log /var/log/nginx/thames.chronosynclabs.com.np-access.log;

        error_log /var/log/nginx/thames.chronosynclabs.com.np-error.log;


        location / {

                proxy_pass http://localhost:3002;

        }


}